import streamlit as st
import pandas as pd
import os

st.set_page_config(
    page_title="Feeder Demand Forecasting & Peak Load Detection",
    layout="wide"
)

st.title("⚡ Feeder Demand Forecasting & Peak Load Detection")
st.markdown(
    """
This dashboard provides a **visual summary** of short-term electricity demand
forecasting and peak load detection for distribution systems.

The results shown here are generated from the analysis notebooks and saved
in the `outputs/` directory.
"""
)

# ------------------ Helper ------------------
def file_exists(path):
    return os.path.exists(path)

# ------------------ Metrics Section ------------------
st.header("📊 Forecasting Performance Metrics")

metrics_path = "outputs/metrics/forecast_metrics.csv"

if file_exists(metrics_path):
    metrics = pd.read_csv(metrics_path)
    st.dataframe(metrics, use_container_width=True)
else:
    st.warning("Forecast metrics not found. Please run the forecasting notebook first.")

# ------------------ Forecast Plot ------------------
st.header("📈 Forecast vs Actual Load")

forecast_plot = "outputs/plots/forecast_vs_actual.png"

if file_exists(forecast_plot):
    st.image(forecast_plot, caption="Short-Term Load Forecast (24–72h)", use_column_width=True)
else:
    st.warning("Forecast plot not found. Please generate plots from the notebook.")

# ------------------ Peak Detection Section ------------------
st.header("🚨 Detected Peak Load Events")

peaks_plot = "outputs/plots/detected_peaks.png"
peaks_metrics = "outputs/metrics/peak_detection_summary.csv"

col1, col2 = st.columns(2)

with col1:
    if file_exists(peaks_plot):
        st.image(peaks_plot, caption="Residual-Based Peak Detection", use_column_width=True)
    else:
        st.warning("Peak detection plot not found.")

with col2:
    if file_exists(peaks_metrics):
        peak_df = pd.read_csv(peaks_metrics)
        st.subheader("Peak Detection Summary")
        st.dataframe(peak_df, use_container_width=True)
    else:
        st.warning("Peak detection metrics not found.")

# ------------------ Footer ------------------
st.markdown("---")
st.markdown(
    """
**Notes**
- This dashboard is intentionally lightweight and read-only.
- Core modeling logic resides in the `src/` module.
- All results must be generated by running the notebooks first.

**Intended Use**
- Interview walkthroughs
- Portfolio demonstrations
- Non-technical stakeholder explanations
"""
)
